### ISSUE TITLE
CREATE FOLDER to store all pp images and update code accordingly

### ISSUE THREAD

**Issue by pranav-bolla** [SuyogKhanal5/LeagueTeamManager#17]

**Comment by MisansProducts** [comment]
Hi! I noticed that your `sravika(ctx)` command is the only command responsible for sending a "pp" image and its purpose is to send a random image, which is similar to my Discord bot. If you follow these changes it should work.

For the libraries, change `from random import randrange` to just `import random` so you have access to all random functions. You are going to be using `random.choice()` to pick a random element from a list. Next, get `import os` so you have access to operating system functions to get the path of files.

Right under the imports, define a variable `ppFolderPath = os.path.join(os.path.dirname(__file__), "ppFolder\\")` to get the path of a folder named "ppFolder". The `os.path.join()` will connect the path of the Python file's directory with your folder that has the images.

Make sure you create a folder to put those pp images inside of in the same directory as the Python file. I called it "ppFolder" but you can call it whatever you want, as long as you change the string "ppFolder\\" in the variable definition above.

Finally, inside your `sravika(ctx)` function, use `os.listdir(ppFolderPath)` to get a list of all the file names inside the pp folder. Use `random.choice()` to pick a random element from that list, and connect it with `os.path.join()` to the pp folder whilst sending it as a message.

Here is the updated code for that function:
```#=====PP IMAGES COMMAND=====
@client.command()
async def sravika(ctx):
    myImages = os.listdir(ppFolderPath) #Gets list of all images in the pp folder
    s = random.choice(myImages) #Picks a random image from the pp folder
    return await ctx.send("le pp", file = discord.File(os.path.join(ppFolderPath, s))) #Connects the path of the pp folder with the name of the picked image
```

Let me know if it works. Remember to create a folder named "ppFolder" and move the images there.
